name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Check out repository
        uses: actions/checkout@v4

      - &setup_go
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
          args: ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup_go

      - name: Run tests
        run: go test ./...

  race:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup_go

      - name: Run tests with the race detector
        run: go test -race ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup_go

      - name: Build all packages
        run: go build ./...
